### ISSUE TITLE
Security Risk on Website

### ISSUE THREAD

**Issue by BenPortner** [mutandon/ExemplarQueries#1]
Hi guys,

Just wanted to let you know that Firefox shows me a "Warning: Potential Security Risk Ahead" when I click on the [link](disi.unitn.it/~lissandrini/exemplar.html) to your website. Is this about your certificate being outdated or is the problem on my side?

Cheers
Ben

**Comment by kuzeko** [comment]
Thanks for checking out. Fixed with new link!

**Comment by BenPortner** [comment]
Hi @kuzeko,

the link in the readme is fixed now. However, the link in the `about`-section is still causing the error.

Another question: I was hoping that I would find a hosted version of your project on the homepage. Is there such a thing? Just want to see what your exemplary queries are like and play a bit 😃 

Cheers
Ben

**Comment by kuzeko** [comment]
Thanks Ben,
we will fix that.

At the moment there is no hosted version, we needed the servers for other things.
But here is the video that shows it: https://www.youtube.com/watch?v=A1_dKvX5ZRk

**Comment by BenPortner** [comment]
Hi @kuzeko,

the video does it! ExemplarQueries looks amazing! Big thumbs up! 👍 😃 

Cheers
Ben
